@echo off
Echo       ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
echo       ³                                                ³
echo       ³         Aguade!!!  Instalando o Sistema        ³
echo       ³                    TEC MAQ                     ³
echo       ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´        
echo       ³ Espere aproximadammente 2 minutos...           ³
echo       ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
md c:\tm
cd c:\tm
c:
a:_tm -y > nul
echo Para entrar no sistema Digite TECMAQ  <ENTER>
ECHO -





