clipper abert001 /m
if not errorlevel = 1 clipper banc000 /m
if not errorlevel = 1 clipper banc001 /m
if not errorlevel = 1 clipper banc002 /m
if not errorlevel = 1 clipper banc003 /m
if not errorlevel = 1 clipper banc004 /m
if not errorlevel = 1 clipper banc005 /m
if not errorlevel = 1 clipper banc006 /m
if not errorlevel = 1 clipper banc007 /m
if not errorlevel = 1 clipper banc008 /m
if not errorlevel = 1 clipper banc009 /m
if not errorlevel = 1 clipper banc010 /m
if not errorlevel = 1 clipper banc011 /m
if not errorlevel = 1 clipper banc013 /m
if not errorlevel = 1 clipper banc014 /m
if not errorlevel = 1 clipper banc015 /m
if not errorlevel = 1 clipper banc016 /m
if not errorlevel = 1 clipper banc017 /m
if not errorlevel = 1 clipper banc018 /m
if not errorlevel = 1 clipper banc019 /m
if not errorlevel = 1 clipper cadusu  /m
if not errorlevel = 1 clipper cscores /m
if not errorlevel = 1 clipper indexa  /m
if not errorlevel = 1 clipper menu001  /m
if not errorlevel = 1 clipper menubanc /m
