
{{"CODIGO    ","C",06,0},;
 {"NOME_FOR  ","C",40,0},; 
 {"VALOR     ","N",10,0},;
 {"DATA_PG   ","D",08,0},;
 {"SELEC     ","C",01,0}} 


{{"CODIGO    ","C",06,0},;
 {"NOME      ","C",40,0},;
 {"RG        ","C",15,0},;
 {"ENDERECO  ","C",40,0},;
 {"TELEFONE  ","C",15,0},; 
 {"CEP       ","C",09,0},;
 {"ESTADO    ","C",02,0},;
 {"INSC      ","C",15,0},;
 {"OBS       ","M",10,0},;
 {"CIDADE    ","C",30,0}}

{{"CODIGO    ","C",06,0},;
 {"PRODUTO   ","C",40,0},;
 {"EMBALAGEM ","C",25,0},;
 {"VALUNIT   ","N",10,2},;
 {"QTD       ","N",04,0},;
 {"QTDMIN    ","N",03,0},;
 {"VALUNITV  ","N",10,2},;
 {"MARCADO   ","C",01,0}}

{{"CODIGO    ","C",06,0},; 
 {"NOME      ","C",40,0},;
 {"RG        ","C",15,0},;
 {"ENDERECO  ","C",40,0},;
 {"TELEFONE  ","C",15,0},;
 {"CEP       ","C",09,0},;
 {"ESTADO    ","C",02,0},;
 {"INSC      ","C",15,0},;
 {"ITEM      ","M",10,0},;
 {"CIDADE    ","C",30,0},;
 {"CPF       ","C",15,0},;
 {"EMPRESA   ","C",30,0}}


{{"DESCRICAO ","C",40,0},;
 {"VALOR     ","N",10,2},;
 {"DATA      ","D",08,0},;
 {"TIPO      ","C",01,0}}

{{"DESCRICAO ","C",40,0},;
 {"VALOR     ","N",10,2},;
 {"DATA      ","D",08,0},;
 {"TIPO      ","C",01,0}}


{{"COD_PES   ","C",06,0},;
 {"PESSOA    ","C",40,0},;
 {"COD_ITEM  ","C",06,0},;
 {"ITEM      ","C",40,0},;
 {"QUANT     ","N",04,0},;
 {"VAL_UNI   ","N",10,2},;
 {"VAL_TOT   ","N",10,2},;
 {"DATA_NEG  ","D",08,2},;
 {"TIPO      ","C",01,0}}}

{{"PEDIDO    ","N",06,0},;
 {"COD_CLI   ","C",06,0},;
 {"DATA      ","D",08,0},;
 {"FAZENDA   ","C",40,0},;
 {"MUNICIPIO ","C",30,0},;
 {"ESTADO    ","C",02,0},;
 {"CONDICAO  ","C",40,0},;
 {"PROG      ","D",08,0},;
 {"OBS       ","C",50,0},; 
 {"ROT_FAZ1  ","C",50,0},;
 {"ROT_FAZ2  ","C",50,0},;
 {"ROT_FAZ3  ","C",50,0}}