
procedure men_t_11
set color to w/n
borda(6,9,19,70)
*set color to w/g
@6, 25 say "Reparos    de    Autos"
do mens
@8,10 say  "Codigo do Cliente:"
@9,10 say  "Nome.............:"
@10,10 say "Codigo da func...:"
@11,10 say "Nome.............:"
borda(12,0,19,79)
@13,10 say "Pecas Consumidas.:"
@14,1 say "Codigo Peca³Descricao Pecas                    ³Quant Comprad  ³Subtotal"
return
***************************