CODIGO     ³ Character ³     5
NOME       ³ Character ³    40
DATINSC    ³ Date      ³     8
PROCEDE    ³ Character ³    35
CIDRES     ³ Character ³    35
INSTRUTORA ³ Character ³     5
DATNASC    ³ Date      ³     8
ENDERECO   ³ Character ³    40
FONERES    ³ Character ³    16
FONETRAB   ³ Character ³    16
SITCONJU   ³ Numeric   ³     1 ³   0
GRINSTRU   ³ Numeric   ³     1 ³   0
NOMECOMP   ³ Character ³    40 ³
ENDCOMP    ³ Character ³    40 ³
FONERESCMP ³ Character ³    16 ³
FONTRABCMP ³ Character ³    16 ³
GRINSTRUCP ³ Numeric   ³     1 ³   0
NRFILHOS   ³ Numeric   ³     2 ³   0
ID_ULT_FIL ³ Numeric   ³     2 ³   0
INDICACAO  ³ Numeric   ³     2 ³   0
ULTMENST   ³ Date      ³     8 ³
PLANFAMI   ³ Numeric   ³     1 ³   0
PLANFAMIPO ³ Numeric   ³     1 ³   0
AMAMENTA   ³ Numeric   ³     1 ³   0
P_PART_AMA ³ Numeric   ³     1 ³   0
ABORTO_RES ³ Numeric   ³     1 ³   0
MENOPAUSA  ³ Numeric   ³     1 ³   0
OVULACAO   ³ Numeric   ³     1 ³   0
CICLOS     ³ Numeric   ³     1 ³   0
PILULAS    ³ Numeric   ³     1 ³   0
NOME_PILU  ³ Character ³    20 ³
ULT_PIL_D  ³ Character ³    10 ³
MOTIVO_PIL ³ Character ³    40 ³
EFEITO_P   ³ Character ³    40 ³
DIU        ³ Numeric   ³     1 ³   0
NOME_DIU   ³ Character ³    20 ³
MOTIVO_DIU ³ Character ³    40 ³
EFEITO_DIU ³ Character ³    40 ³
ENGR_PIL   ³ Numeric   ³     1 ³   0
ENGR_DIU   ³ Numeric   ³     1 ³   0
MART_ANT_P ³ Numeric   ³     1 ³   0
MART_ANT_D ³ Numeric   ³     1 ³   0
MART_ANT_C ³ Numeric   ³     1 ³   0
MART_ANT_E ³ Numeric   ³     1 ³   0
ENGR_MART  ³ Numeric   ³     1 ³   0
ENG_MART_N ³ Character ³    25 ³
ENG_MART_T ³ Date      ³     8 ³
MOT_OVOLU  ³ Character ³     1 ³
SITUACAO   ³ Numeric   ³     1 ³   0
SITUA_1    ³ Numeric   ³     2 ³   0
